// react-demo-classcomponent-people/src/App.jsx
import React, { Component } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import PersonCard from './PersonCard';

class App extends Component {
  state = {
    people: [{
      name: "Gipsz Jakab",
      email: "gipsz@example.com",
      age: 42,
    },
    {
      name: "Gipsz Jakab",
      email: "gipsz@example.com",
      age: 42,
    },
    {
      name: "Gipsz Jakab",
      email: "gipsz@example.com",
      age: 42,
    },
    {
      name: "Gipsz Jakab",
      email: "gipsz@example.com",
      age: 42,
    },
    {
      name: "Gipsz Jakab",
      email: "gipsz@example.com",
      age: 42,
    }],
    person: {
      name: "",
      email: "",
      age: 0,
    }
  };

  render() {
    const { people, person } = this.state;
    const cardList = [];
    people.forEach((person) => {
      cardList.push(<PersonCard person={person} key={person} />);
    });

    return (
      <main className="container">
        <form className="mt-1" onSubmit={(e) => this.add_person(e)}>
          <h2>Add new person</h2>
          <div className="mb-3">
            <label htmlFor="name_input">Name</label>
            <input
              className="form-control"
              type="text"
              id="name_input"
              placeholder="Name"
              required
              value={person.name}
              onInput={(event) => this.setPersonName(event.target.value)}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="email_input">Email</label>
            <input
              className="form-control"
              type="email"
              id="email_input"
              placeholder="Email"
              required
              value={person.email}
              onInput={(event) => this.setPersonEmail(event.target.value)}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="age_input">Age</label>
            <input
              className="form-control"
              type="number"
              id="age_input"
              placeholder="Age"
              required
              value={person.age}
              onInput={(event) => this.setPersonAge(event.target.value)}
            />
          </div>
          <button className="btn btn-primary" type="submit">
            Submit
          </button>
        </form>
        <section className="row mt-3 gy-3">{cardList}</section>
      </main>
    );
  }

  add_person = (e) => {
    e.preventDefault();
    const { people, person } = this.state;
    const newPeople = [];
    people.forEach(p1 => {
      newPeople.push(p1);
    });
    newPeople.push(person);
    this.setState({people: newPeople});
  }

  setPersonName = (value) => {
    const { person } = this.state;
    this.setState({person: {
      name: value,
      email: person.email,
      age: person.age,
    }});
  }

  setPersonEmail = (value) => {
    const { person } = this.state;
    this.setState({person: {
      name: person.name,
      email: value,
      age: person.age,
    }});
  }

  setPersonAge = (value) => {
    const { person } = this.state;
    this.setState({person: {
      name: person.name,
      email: person.email,
      age: value,
    }});
  }

}

export default App;

// vue-demo-people/src/App.vue
<script>
import "bootstrap/dist/css/bootstrap.min.css";
import PersonCard from "./components/PersonCard.vue";

export default {
  components: {
    PersonCard,
  },
  data() {
    return {
      people: [
        {
          name: "Gipsz Jakab",
          email: "gipsz@example.com",
          age: 42,
        },
        {
          name: "Gipsz Jakab",
          email: "gipsz@example.com",
          age: 42,
        },
        {
          name: "Gipsz Jakab",
          email: "gipsz@example.com",
          age: 42,
        },
        {
          name: "Gipsz Jakab",
          email: "gipsz@example.com",
          age: 42,
        },
        {
          name: "Gipsz Jakab",
          email: "gipsz@example.com",
          age: 42,
        },
      ],
      person: {
        name: "",
        email: "",
        age: 0,
      },
    };
  },
  methods: {
    add_person(e) {
      e.preventDefault();
      this.people.push(this.person);
      this.person = {
        name: "",
        email: "",
        age: 0,
      };
    },
  },
};
</script>

<template>
  <main class="container">
    <form class="mt-3" @submit="add_person">
      <div class="mb-3">
        <label for="name_input">Name</label>
        <input
          class="form-control"
          type="text"
          id="name_input"
          placeholder="Name"
          required
          v-model="person.name"
        />
      </div>
      <div class="mb-3">
        <label for="email_input">Email</label>
        <input
          class="form-control"
          type="email"
          id="email_input"
          placeholder="Email"
          required
          v-model="person.email"
        />
      </div>
      <div class="mb-3">
        <label for="age_input">Age</label>
        <input
          class="form-control"
          type="number"
          id="age_input"
          placeholder="Age"
          required
          v-model="person.age"
        />
      </div>
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    <section class="row mt-4 gy-3">
      <PersonCard v-for="person in people" :person="person" :key="person" />
    </section>
  </main>
</template>
