// vue-demo-people/src/components/PersonCard.vue
<template>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">{{ person.name }}</div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ person.email }}</li>
        <li class="list-group-item">{{ person.age }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    person: Object,
  },
};
</script>

// react-demo-classcomponent-people/src/PersonCard.jsx
import React, { Component } from "react";

class PersonCard extends Component {
  render() {
    const { person } = this.props;
    return (
      <div className="col-md-4">
        <div className="card">
          <div className="card-header">{person.name}</div>
          <ul className="list-group list-group-flush">
            <li className="list-group-item"> {person.email} </li>
            <li className="list-group-item"> {person.age} </li>
          </ul>
        </div>
      </div>
    );
  }
}

export default PersonCard;
